version: '3.8'
services:
  app:
    image: fam4christ
    build: 
      context: ./
      target: production
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    ports:
      - "3000:3000"
    env_file:
      - .env