name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Pull Docker image
        run: sudo docker pull adhuhuri/fam4christ:latest
      - name: Delete Old docker container
        run: sudo docker rm -f fam4christ-container || true
      - name: Run Docker Container
        run: sudo docker run --env-file ~/.env -d -p 3000:3000 --name fam4christ-container adhuhuri/fam4christ
