name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Pull Docker image
        run: sudo docker pull adhuhuri/fam4christ:latest
      - name: Delete Old docker container
        run: sudo docker rm -f fam4christ || true
      - name: Run Docker Container
        run: |
          sudo docker run -d -p 3000:3000 --env-file ~/app/.env --name fam4christ adhuhuri/fam4christ
          sudo docker exec -it fam4christ bash
          npx prisma generate --no-engine
          exit
          sudo docker restart fam4christ
